CREATE SCHEMA IF NOT EXISTS BUUK;

SET SCHEMA BUUK;

/************************************************/
/* USER  */
/************************************************/

CREATE TABLE BUUK.BOOK (
    ID            NUMBER          NOT NULL,
    TITLE         VARCHAR2(100)   NOT NULL,
    AUTHOR        VARCHAR2(100),
    ISBN          VARCHAR2(100),
    RELEASE_DATE  int,
    LENGTH        int
);

ALTER TABLE BUUK.BOOK ADD CONSTRAINT USER_PK PRIMARY KEY (ID);

CREATE SEQUENCE BUUK.EXCHANGE_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;

INSERT INTO BUUK.BOOK (ID, TITLE, AUTHOR, ISBN, RELEASE_DATE, LENGTH)
VALUES (BUUK.EXCHANGE_ID_SEQ.nextval, 'A Morte de Ivan Ilitch','Liev Tolstói', '85-00-1610-2',1886, 138);

INSERT INTO BUUK.BOOK (ID, TITLE, AUTHOR, ISBN, RELEASE_DATE, LENGTH)
VALUES (BUUK.EXCHANGE_ID_SEQ.nextval, 'Graça Infinita','David Foster Wallace', '85-00-1620-5',1996, 1.079);

INSERT INTO BUUK.BOOK (ID, TITLE, AUTHOR, ISBN, RELEASE_DATE, LENGTH)
VALUES (BUUK.EXCHANGE_ID_SEQ.nextval, 'O Velho e O Mar','Ernest Hemingway', '99-99-9999-5',1952, 1.079);